# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fabiomiranda.me" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Fábio Miranda
  avatar:
  gravatar: # Email MD5 hash
  description: "Blog de tecnologia, programação e outras bacanidades." # used by search engines

  # Header and footer text
  header_text: >
     <p>Engenheiro de Software e Apaixonado por Ciências.</p>
  header_text_feature_image:
  footer_text: >
   Desenvolvido com <a href="http://jekyllrb.com">Jekyll</a> e ❤

  # Icons
  rss: false
  email_address: fabiomirandadev@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "fabioviannatj"
  flickr:
  github: "fabiomirandaa"
  google_plus: +fabiomirandatj
  instagram: fabiomirandatj
  linkedin:  https://www.linkedin.com/in/fabiomirandasilva
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "fabiomirandadev"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-83428869-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: fabiomiranda
  katex: true # Enable if using math markup
  search: false

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue lendo"
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
permalink: /:title/
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
