# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fabiodemiranda.com.br" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Fábio Miranda
  avatar:
  gravatar: # Email MD5 hash
  description: "Blog de tecnologia, programação, Angular, Javascript, Typescript, RxJs, NGRX, NGXS e Flutter." # used by search engines

  # Header and footer text
  header_text: >
     <p>Engenheiro de Software, especialista em Angular, RxJS, Typescript. Agora, também youtuber!</p>
  header_text_feature_image:
  footer_text: >
   Desenvolvido com <a href="http://jekyllrb.com">Jekyll</a> e ❤

  # Icons
  rss: false
  email_address: fabiomirandadev@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "fabioviannatj"
  flickr:
  github: "fabiomirandaa"
  google_plus:
  instagram: fabiomirandadev
  linkedin:  https://www.linkedin.com/in/fabiomirandasilva
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "fabiomirandadev"
  wordpress:
  youtube:
  author: "Fábio Miranda"

  # Scripts
  google_analytics: UA-83428869-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: fabiomiranda
  katex: true # Enable if using math markup
  search: true

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Próximo"
  str_prev: "Anterior"
  str_continue_reading: "Continue lendo"
  str_search_no_results: "Nenhum resultado encontrado =( "

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
permalink: /:title/
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate,jekyll-seo-tag,jekyll-sitemap,jemoji]
exclude:
  - Gemfile
  - Gemfile.lock
